a = input('Digite algo:  ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços?', a.isspace())
print('Só tem números?', a.isnumeric())
print('Só tem letras?', a.isalpha())
print('Tá só em letra maiúscula?', a.isupper())
print('Tá só em letra minúscula?', a.islower())
print('É alfanúmerico?', a.isalnum())
print('É capitalizado?', a.istitle())
